rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'

urlpatterns = [
url(r'^$', views.index, name='index'),
url(r'about/$', views.about, name='about'),
url(r'^add_category/$', views.add_category, name='add_category'),
url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
]

tango_with_django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rango import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
url(r'^$', views.index, name='index'),
url(r'^rango/', include('rango.urls')),
url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
views.show_category, name='show_category'),
]

rango/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
        
        
class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    # Override the __unicode__() method to return out something meaningful!
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://', prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them...
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        #or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)
    
    class Meta:
        model = UserProfile
        exclude = ('user',)

rango/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from rango.forms import CategoryForm


from django.shortcuts import render

from django.http import HttpResponse
from rango.models import Category
from rango.models import Page
from rango.forms import PageForm
from rango.forms import CategoryForm

def index(request):
    # Query the database for a list of ALL categories currently stored.
    # Order the categories by no. likes in descending order.
    # Retrieve the top 5 only - or all if less than 5.
    # Place the list in our context_dict dictionary
    # that will be passed to the template engine.
    category_list = Category.objects.order_by('-likes')[:5]
    most_views_category_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'views':most_views_category_list}
    # Render the response and send it back!
    return render(request, 'rango/index.html', context_dict)

def about(request):
    # prints out whether the method is a GET or a POST
    print(request.method)
    # prints out the user name, if no one is logged in it prints `AnonymousUser`
    print(request.user)
    return render(request, 'rango/about.html', {})

def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        # Retrieve all of the associated pages.
        # Note that filter() will return a list of page objects or an empty list
        pages = Page.objects.filter(category=category)
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
     
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
        
        # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context_dict)

def add_category(request):
    form = CategoryForm()
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)
    # Have we been provided with a valid form?
    if form.is_valid():
    # Save the new category to the database.
        form.save(commit=True)
        # Now that the category is saved
        # We could give a confirmation message
        # But since the most recent category added is on the index page
        # Then we can direct the user back to the index page.
        return index(request)
    else:
        # The supplied form contained errors -
        # just print them to the terminal.
        print(form.errors)
        # Will handle the bad form, new form, or no form supplied cases.
        # Render the form with error messages (if any).
        return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
            else:
                print(form.errors)
    context_dict = {'form':form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

templates/rango/about.html
<!DOCTYPE html>

{% load staticfiles %} 

<html>
	<body>
		<div> 
			Rango says here is the about page. 
			<a href="/rango/">Index</a><br />
		</div>
		
		<div>
			<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" /> 
			This tutorial has been put together by Ming Wu.
			<img src={% static "/media/cat.jpg" %}" alt= "Picture of Cat" /> 
		</div>

	</body></html>

templates/rango/add_category.html
<!DOCTYPE html>
<html>
	<head>
		<title>Rango</title>
	</head>
	
	<body>
		<h1>Add a Category</h1>
		<div>
			<form id="category_form" method="post" action="/rango/add_category/">
				{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				{% for field in form.visible_fields %}
					{{ field.errors }}
					{{ field.help_text }}
					{{ field }}
				{% endfor %}
				<input type="submit" name="submit" value="Create Category" />
			</form>
		</div>
	</body>
</html>

templates/rango/add_page.html
<!DOCTYPE html>
	<html>
	    <head>
	        <title>Rango - Add Page</title>
	    </head>

	    <body>
			{% if category %}
			
	        <h1>Add a Page to {{category.name}}</h1>

	        <form id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">

	            {% csrf_token %}
	            {% for hidden in form.hidden_fields %}
	                {{ hidden }}
	            {% endfor %}

	            {% for field in form.visible_fields %}
	                {{ field.errors }}
	                {{ field.help_text }}
	                {{ field }}
	            {% endfor %}

	            <input type="submit" name="submit" value="Add Page" />
	        </form>
			
			{% else %}
				The specified category does not exist!

			{% endif %}
	    </body>

	</html>
		

templates/rango/base.html
{% extends 'rango/base.html' %}
{% load rango_template_tags %}
{% load staticfiles %}

<div>
	{% block sidebar_block %}
		{% get_category_list %}
	{% endblock %}
</div>
<div>
	{% block sidebar_block %}
		{% get_category_list category %}
	{% endblock %}
</div>
{% block title_block %}
	{{ category.name }}
{% endblock %}

{% block body_block %}
	{% if category %}
		<h1>{{ category.name }}</h1>

		{% if pages %}
			<ul>
			{% for page in pages %}
				<li><a href="{{ page.url }}">{{ page.title }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<strong>No pages currently in category.</strong>
		{% endif %}
		<a href="{% url 'add_page' category.slug %}">Add a Page</a>
	{% else %}
		The specified category does not exist!
	{% endif %}
{% endblock %}

templates/rango/category.html
<!DOCTYPE html>
<html>
<head>
	<title>Rango - category</title>
</head>
<body>
	<div>
	{% if category %}
		<h1>{{ category.name }}</h1>
 		{% if pages %}
			 <ul>
			 {% for page in pages %}
				<li><a href="{{ page.url }}">{{ page.title }}</a></li>
			{% endfor %}
			</ul>
 		{% else %}
			<strong>No pages currently in category.</strong>
		{% endif %}
	{% else %}
 		The specified category does not exist!
	{% endif %}
	{% if category %}
		<a href="/rango/category/{{category.slug}}/add_page/">Add Page</a> <br/>
	{% endif %}
	<a href="/rango">Index</a><br />
	
	
 	</div>
</body>
</html>

templates/rango/cats.html
{% for c in cats %}
	{% if c == act_cat %}
		<li>
		<strong>
			<a href="{% url 'show_category' c.slug %}">{{ c.name }}</a>
		</strong>
		</li>
	{% else %}
		<li>
			<a href="{% url 'show_category' c.slug %}">{{ c.name }}</a>
		</li>
	{% endif %}
{% endfor %}

templates/rango/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<title>Rango</title>
	</head>
	<body>
		<h1>Rango says...</h1>
		<div>hey there partner!</div>
		<h2>Most Liked Categories </h2>
		<div>
		{% if categories %}
		<ul>
			{% for category in categories %}
			<li>
				<a href="{% url 'show_category' category.slug %}">
					{{ category.name }}
				</a>
			</li>
		{% endfor %}
		</ul>
		{% else %}
			<strong>There are no categories present.</strong>
		{% endif %}

		<h2> Most Viewed Pages </h2>
		{% if views %}
		<ul>
			{% for view in views %}
			<li>
			<a href="{{ view.url }}">{{ view.title }}</a>
			</li>
			{% endfor %}
		</ul>
		{% else %}
			<strong>There are no views present.</strong>
		{% endif %}


		</div>
		<div>
			<a href="/rango/add_category/">Add a New Category</a><br />
			<a href="{% url 'rango:about' %}">About</a>
			
			<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
		</div>
	</body>
</html>